### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by JahidFariz** [JahidFariz/Remote-Keylogger#1]
[ENVIRONMENT]
Python Version: 3.8.10
Operating System: Linux

[TEST-CASE]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kali/Remote-Keylogger/./__main__.py", line 41, in <module>
    base_path: str | bytes = split(p=__file__)[0]
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by JahidFariz** [comment]
We fixed this error by modifying the line 41:

Before > base_path: str | bytes = split(p=file)[0]
After > base_path = split(p=file)[0]

This error occurs on only python 3.9 and below.

**Comment by JahidFariz** [comment]
[ENVIRONMENT]
Python Version: 3.8.10
Operating System: Windows

[TEST-CASE]
Traceback (most recent call last):
  File "C:\Program Files\Python38-32\lib\runpy.py", line 194, in _run_module_as_
main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Downloads\Remote-Keylogger-main\.\__main__.py", line 60, i
n <module>
    app: None | Tk = None
TypeError: unsupported operand type(s) for |: 'NoneType' and 'type'

**Comment by JahidFariz** [comment]
We fixed this error by modifying the line 60:

Before > app: None | Tk = None
After > app = None

This error occurs on only python version 3.9 and below.
